# Generated by Django 5.2 on 2025-05-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoice", "0001_initial"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_invoices",
                related_query_name="SubscriptionInVoice",
                to="subscription.subscription",
            ),
        ),
    ]
